-- =============================================================
-- DQ (table): dq_partition_reconciliation
-- Source: data/_manifest/expected_partitions.csv vs the raw feeds
-- Grain: one row per (feed, partition).
--
-- The ingestion job records an expected row count for every partition
-- it writes. 02_Feed_Contracts.md says of that manifest: "Intended for
-- reconciliation. It has never actually been used for that." This model
-- uses it, which closes ticket KP-3168 (no reconciliation step of any
-- kind in the nightly script).
--
-- WHAT THIS CATCHES that nothing else does: a partition that is present
-- and readable but SHORT. On this dataset it isolates DEFECT L18 - one
-- truncated Parquet file in reefer_telemetry/dt=2025-07-14, 945 rows
-- missing against a manifest expectation of 6,724. No amount of
-- querying the loaded tables would reveal that, because the rows are
-- simply not there to be counted.
--
-- WHAT IT CANNOT CATCH, and this is the important limitation: the
-- manifest is generated by scanning the partitions that were actually
-- written. A day the ingestion job never wrote at all is absent from
-- BOTH sides and reconciles clean. Detecting that needs a calendar
-- spine - see dq_feed_completeness.
--
-- CONTROL GAP - erp_cdc is not in the manifest at all. The manifest
-- covers pos_transactions, reefer_telemetry and wms_scan_events only.
-- All three ERP CDC feeds - outlet_master, product_master and
-- sales_order_header - have no reconciliation baseline whatsoever, so
-- one of the four source systems cannot be reconciled even in
-- principle. That is recorded as explicit NO_MANIFEST_BASELINE rows
-- below rather than left as a silent absence, because an unmonitored
-- feed that looks fine is the failure mode this whole model exists to
-- prevent.
--
-- The truncated file is excluded by name when counting, exactly as
-- stg_reefer_telemetry does - read_parquet fails hard on a corrupt file
-- otherwise, and one bad file must not take the pipeline down. The
-- shortfall it causes is still reported in full below; skipping the
-- file suppresses the crash, not the finding.
-- =============================================================

CREATE OR REPLACE TABLE dq_partition_reconciliation AS

WITH manifest AS (
    SELECT
        feed,
        partition,
        file_count  AS expected_files,
        row_count   AS expected_rows,
        bytes       AS expected_bytes
    FROM read_csv(
        getvariable('data_root') || '/_manifest/expected_partitions.csv',
        header = true
    )
),

actual_pos AS (
    SELECT 'pos_transactions' AS feed,
           'ingest_date=' || CAST(ingest_date AS VARCHAR) AS partition,
           count(*) AS actual_rows
    FROM read_parquet(
        getvariable('data_root') || '/raw/pos_transactions/**/*.parquet',
        union_by_name = true, hive_partitioning = true
    )
    GROUP BY 1, 2
),

actual_reefer AS (
    SELECT 'reefer_telemetry' AS feed,
           'dt=' || CAST(dt AS VARCHAR) AS partition,
           count(*) AS actual_rows
    FROM read_parquet(
        getvariable('data_root') || '/raw/reefer_telemetry/**/*.parquet',
        hive_partitioning = true, filename = true
    )
    -- DEFECT L18: skip the truncated file, report its shortfall.
    WHERE filename NOT LIKE '%dt=2025-07-14/part-00000.parquet'
    GROUP BY 1, 2
),

actual_wms AS (
    SELECT 'wms_scan_events' AS feed,
           'dt=' || CAST(dt AS VARCHAR) AS partition,
           count(*) AS actual_rows
    FROM read_parquet(
        getvariable('data_root') || '/raw/wms_scan_events/**/*.parquet',
        hive_partitioning = true
    )
    GROUP BY 1, 2
),

actual AS (
    SELECT * FROM actual_pos
    UNION ALL SELECT * FROM actual_reefer
    UNION ALL SELECT * FROM actual_wms
),

reconciled AS (
    SELECT
        COALESCE(m.feed, a.feed)           AS feed,
        COALESCE(m.partition, a.partition)  AS partition,
        m.expected_rows,
        COALESCE(a.actual_rows, 0)          AS actual_rows,
        COALESCE(a.actual_rows, 0) - m.expected_rows AS row_delta,
        m.expected_files,
        m.expected_bytes
    FROM manifest m
    FULL OUTER JOIN actual a
      ON m.feed = a.feed AND m.partition = a.partition
),

-- Feeds with no manifest coverage at all. Recorded, not omitted.
unmonitored AS (
    SELECT feed, 'ALL' AS partition,
           NULL::BIGINT AS expected_rows, count(*) AS actual_rows,
           NULL::BIGINT AS row_delta,
           NULL::BIGINT AS expected_files, NULL::BIGINT AS expected_bytes
    FROM (
        SELECT 'erp_cdc/outlet_master' AS feed
        FROM read_parquet(getvariable('data_root') || '/raw/erp_cdc/outlet_master/**/*.parquet',
                          hive_partitioning = true)
        UNION ALL
        SELECT 'erp_cdc/product_master'
        FROM read_parquet(getvariable('data_root') || '/raw/erp_cdc/product_master/**/*.parquet',
                          hive_partitioning = true)
        UNION ALL
        SELECT 'erp_cdc/sales_order_header'
        FROM read_parquet(getvariable('data_root') || '/raw/erp_cdc/sales_order_header/**/*.parquet',
                          hive_partitioning = true)
    )
    GROUP BY feed
)

SELECT
    feed,
    partition,
    expected_rows,
    actual_rows,
    row_delta,
    ROUND(100.0 * actual_rows / NULLIF(expected_rows, 0), 4) AS pct_of_expected,
    expected_files,
    expected_bytes,
    CASE
        WHEN expected_rows IS NULL AND partition = 'ALL' THEN 'NO_MANIFEST_BASELINE'
        WHEN expected_rows IS NULL                        THEN 'UNEXPECTED_PARTITION'
        WHEN actual_rows = 0                              THEN 'PARTITION_UNREADABLE'
        WHEN actual_rows < expected_rows                  THEN 'SHORTFALL'
        WHEN actual_rows > expected_rows                  THEN 'SURPLUS'
        ELSE 'MATCH'
    END AS status
FROM (SELECT * FROM reconciled UNION ALL SELECT * FROM unmonitored)
ORDER BY
    CASE WHEN COALESCE(row_delta, 0) <> 0 OR expected_rows IS NULL THEN 0 ELSE 1 END,
    feed, partition;
